name: Deployment Workflow

on:
  push:
    branches:
      - release
      - preprod
      - prod
      - dev

jobs:
  verify-build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint

    - name: Run tests
      env:
        TEST_DB_URI: ${{ secrets.TEST_DB_URI }}
      run: npm test

    - name: Build project
      run: npm run build
    
    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.ENV_SECRETS }}" >> .env

    - name: Deploy to EC2
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: './'
        remote_path: ${{ secrets.REMOTE_DIR }}
        remote_host: ${{ secrets.REMOTE_HOST }}
        remote_user: ${{ secrets.REMOTE_USER }}
        remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"